### ISSUE TITLE
Deleting Projects after Exporting as XML

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#50]
There is an issue here but it took sometime to work out. It appears that after a project has been exported as an XML file it is no longer possible to Delete that project. The warning that appears is ' NOT NULL constraint failed: Manhole.Project_Id'

And then after that if I close that warning and select a Project I get this,

'EntryAssembly: C:\Users\Main\Desktop\New Folder (3)\Release\ManholeReport.exe
UnhandledException:
Member 'Reload' cannot be called for the entity of type 'Project' because the entity does not exist in the context. To add an entity to the context call the Add or Attach method of DbSet<Project>.
StackTrace:
   at System.Data.Entity.Internal.InternalEntityEntry.Reload()
  at ManholeReport.Model.ManholeReportDbDataModel.Common.DataModel.EntityFramework.DbRepository`3.ReloadCore(TEntity entity)
  at ManholeReport.Model.ManholeReportDbDataModel.Common.DataModel.EntityFramework.DbRepository`3.ManholeReport.Model.Common.DataModel.IRepository<TEntity,TPrimaryKey>.Reload(TEntity entity)
  at ManholeReport.Model.Common.ViewModel.CollectionViewModelBase`3.Select(TEntity entity)
  at ManholeReport.ViewModels.ProjectCollectionViewModel.Select(Project entity)
  at DevExpress.Mvvm.UI.EventToCommand.Invoke(Object sender, Object eventArgs)
  at DevExpress.Mvvm.UI.EventToCommandBase.OnEventCore(Object sender, Object eventArgs)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
  at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
  at System.Windows.Input.InputManager.ProcessStagingArea()
  at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
  at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
  at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Application.RunInternal(Window window)
  at System.Windows.Application.Run()
  at ManholeReport.App.Main()

And when I close that the program closes.

**Comment by Viewline-MH** [comment]
Actually this error might be thrown by something else. I now think it is related to something else. It is possible to delete a project if there is no data within it (no Manholes or Assets). So I revisited Projects with Manholes and Assets and deleted these as a test. What I found was it was simple to delete all apart from the final Manhole or Asset. 
I'll have to continue with this as I've noticed something odd that might be related.
