### ISSUE TITLE
1st Manhole First Project

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#53]
It seems that if I remove all the projects and then start again there is always an issue when I have created the first Project and then the first Manhole, either a warning is shown or the loading box is shown and nothing happens, like it's caught in a loop. 

Then it is noticeable that if I only add one Manhole to each Project I get some kind of issue frequently but not always. This looks like an intermittent issue that I can't really understand.

**Comment by Viewline-MH** [comment]
Still there. Exception message below:

EntryAssembly: C:\Users\Ian\Desktop\Release\ManholeReport.exe
UnhandledException:
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
  at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at DevExpress.Mvvm.Native.WeakReferenceActionInvoker`1.Execute(T parameter)
  at DevExpress.Mvvm.Native.ActionInvokerBase`1.DevExpress.Mvvm.Native.IActionInvoker.ExecuteIfMatched(Type messageTargetType, Object parameter)
  at DevExpress.Mvvm.Messenger.ActionInvokerCollection.Send(Object message, Type messageTargetType, Object token, Type messageType)
  at DevExpress.Mvvm.Messenger.Send[TMessage](TMessage message, Type messageTargetType, Object token)
  at ManholeReport.Model.Common.ViewModel.SingleObjectViewModelBase`3.Save() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\SingleObjectViewModel.cs:line 113
  at ManholeReport.Model.Common.ViewModel.SingleObjectViewModel`3.SaveAndClose() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\SingleObjectViewModel.partial.cs:line 55
  at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
  at System.Windows.Controls.Primitives.ButtonBase.OnClick()
  at System.Windows.Controls.Button.OnClick()
  at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
  at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
  at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
  at System.Windows.Input.InputManager.ProcessStagingArea()
  at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
  at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
  at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Application.RunDispatcher(Object ignore)
  at System.Windows.Application.RunInternal(Window window)
  at ManholeReport.App.Main() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\Manholereport\obj\Release\App.g.cs:line 0
InnerException:
	Object reference not set to an instance of an object.
	StackTrace:
	   at lambda_method(Closure , Manhole )
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModelBase`3.Edit(TEntity entity) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\CollectionViewModel.cs:line 96
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModel`3.OnEntityAdded(TPrimaryKey key) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\CollectionViewModel.partial.cs:line 31
