### ISSUE TITLE
Deleting Manholes

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#54]
I find that sometimes when deleting manholes from Projects with more than one Manhole I am getting this message and the App fails:

EntryAssembly: C:\Users\Main\Desktop\New Folder (3)\Release\ManholeReport.exe
UnhandledException:
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
  at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
  at DevExpress.Mvvm.Messenger.ActionInvokerCollection.Send(Object message, Type messageTargetType, Object token, Type messageType)
  at DevExpress.Mvvm.Messenger.Send[TMessage](TMessage message, Type messageTargetType, Object token)
  at ManholeReport.Model.Common.ViewModel.CollectionViewModelBase`3.Delete(TEntity entity)
  at System.Windows.Controls.Button.OnClick()
  at DevExpress.Xpf.WindowsUI.AppBarButtonBase.OnClick()
  at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
  at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
  at System.Windows.Input.InputManager.ProcessStagingArea()
  at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
  at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
  at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Application.RunInternal(Window window)
  at System.Windows.Application.Run()
  at ManholeReport.App.Main()
InnerException:
	Object reference not set to an instance of an object.
	StackTrace:
	   at ManholeReport.ViewModels.ManholeCollectionViewModel.<ManholeEntityUpdated>b__1(Manhole ent)
	  at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
	  at ManholeReport.ViewModels.ManholeCollectionViewModel.ManholeEntityUpdated(Object sender, EventArgs e)
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModel`3.OnEntityDeleted(TPrimaryKey key)
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModelBase`3.OnMessage(EntityMessage`1 message)
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModelBase`3.<OnInitializeInRuntime>b__0(EntityMessage`1 x)

**Comment by Viewline-MH** [comment]
Seems good now.
