### ISSUE TITLE
Slow loading or not loading Manholes and Assets

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#59]
I see this intermittently but regularly when I create a Manhole or an Asset. The thumbprint icon is displayed and the loading message is displayed for quite a long time before the form slides in. Sometimes the loading message just remains and the form never slides in. 

I think there maybe some relation to using a previously used reference (in another project) but I'm not sure. I say this based on tests that involve using deliberately unique Manhole and Asset refs and getting no problems and then testing with Manhole and Asset references that I know have been used in other saved projects and getting problems.

So to be clear; all projects should be unique (no duplicate project names) and Manholes and Assets should be unique within their project only.

**Comment by Viewline-MH** [comment]
This might be useful. I noticed the slow loading issue only once when creating a Manhole on my home PC. I opened the task manager to get out of this and saw 4 Release folders in the Applications list. This was odd. I ended all these tasks and then killed the process. I then opened the application and immediately looked at the task manager and there were no Release folders in the Application list just one Manhole Report app as you would expect. Then I tried to create a new manhole and it went into the not loading loop. Opened Task Manager and there was just the Manhole Report app showing in applications, I ended that task but to close the app I had to end the process. So I opened it again, opened the manholes and returned to the manhole that was created (even though the app had frozen), added 2 pictures, opened the task manager and I could see the application and a Release folder in the Applications list. So then I created a new project  and added a new manhole and the app went into the loading loop, so I closed the application using the top right close button but the loading timer was still going so I opened the task manager and I could NOT see the Manhole Report App but there was a Release folder, which I closed using the End Task but this did nothing, so I closed the process.
One thing I have noticed is when the app starts to do this not loading thing it seems to do very regular after the initial one.

**Comment by armandomusto** [comment]
Can you send me a screenshot of Task list? I did not understand what is the Release folder you are talking about

**Comment by Viewline-MH** [comment]
I think the problem is related mainly to when the 1st manhole is created on a New Project. I find that if I use a manhole reference previously used in the preceding project on creation of the first manhole, then I always get this issue. If I create a project and create the first manhole with a previously unused manhole reference, I some times get this error and sometimes I don't. 
After the App has been closed, reopened and I revisit the last project where I've just had an issue, I can enter manhole references that are the same as manhole references used in the previous project and I don't seem to get this problem.
I'm hoping if you duplicate the tests outlined above you should get the same error.

**Comment by Viewline-MH** [comment]
Still getting this issue when creating a new manhole or asset:
EntryAssembly: C:\Users\Ian\Desktop\Manhole_18\Release\ManholeReport.exe
UnhandledException:
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
  at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at DevExpress.Mvvm.Native.WeakReferenceActionInvoker`1.Execute(T parameter)
  at DevExpress.Mvvm.Native.ActionInvokerBase`1.DevExpress.Mvvm.Native.IActionInvoker.ExecuteIfMatched(Type messageTargetType, Object parameter)
  at DevExpress.Mvvm.Messenger.ActionInvokerCollection.Send(Object message, Type messageTargetType, Object token, Type messageType)
  at DevExpress.Mvvm.Messenger.Send[TMessage](TMessage message, Type messageTargetType, Object token)
  at DevExpress.Mvvm.MessengerExtensions.Send[TMessage](IMessenger messenger, TMessage message)
  at ManholeReport.Model.Common.ViewModel.SingleObjectViewModelBase`3.Save() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\SingleObjectViewModel.cs:line 113
  at ManholeReport.Model.Common.ViewModel.SingleObjectViewModel`3.SaveAndClose() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\SingleObjectViewModel.partial.cs:line 55
  at DevExpress.Mvvm.DelegateCommand.<>c__DisplayClass4.<.ctor>b__0(Object o)
  at DevExpress.Mvvm.DelegateCommand`1.Execute(T parameter)
  at DevExpress.Mvvm.CommandBase`1.System.Windows.Input.ICommand.Execute(Object parameter)
  at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
  at System.Windows.Controls.Primitives.ButtonBase.OnClick()
  at System.Windows.Controls.Button.OnClick()
  at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
  at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
  at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
  at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
  at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
  at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
  at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
  at System.Windows.Input.InputManager.ProcessStagingArea()
  at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
  at System.Windows.Input.StylusLogic.PromoteMainToMouse(StagingAreaInputItem stagingItem)
  at System.Windows.Input.StylusLogic.PromoteMainUpToTouch(StylusDevice stylusDevice, StagingAreaInputItem stagingItem)
  at System.Windows.Input.StylusLogic.PromoteMainToTouch(ProcessInputEventArgs e, StylusEventArgs stylusEventArgs)
  at System.Windows.Input.StylusLogic.PromoteMainToOther(ProcessInputEventArgs e)
  at System.Windows.Input.StylusLogic.PostProcessInput(Object sender, ProcessInputEventArgs e)
  at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
  at System.Windows.Input.InputManager.ProcessStagingArea()
  at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
  at System.Windows.Input.StylusLogic.InputManagerProcessInput(Object oInput)
  at System.Windows.Input.StylusLogic.PreProcessInput(Object sender, PreProcessInputEventArgs e)
  at System.Windows.Input.InputManager.ProcessStagingArea()
  at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
  at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
  at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
  at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
  at System.Windows.Application.RunDispatcher(Object ignore)
  at System.Windows.Application.RunInternal(Window window)
  at System.Windows.Application.Run(Window window)
  at ManholeReport.App.Main() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\Manholereport\obj\Release\App.g.cs:line 0
InnerException:
	Object reference not set to an instance of an object.
	StackTrace:
	   at ManholeReport.ViewModels.ManholeCollectionViewModel.Manhole_EntityAdded(Object sender, EventArgs e) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\Manholereport\ViewModels\Manhole\ManholeCollectionViewModel.cs:line 199
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModel`3.OnEntityAdded(TPrimaryKey key) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\CollectionViewModel.partial.cs:line 32
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModelBase`3.OnMessage(EntityMessage`1 message) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\CollectionViewModel.cs:line 215
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModelBase`3.<OnInitializeInRuntime>b__0(EntityMessage`1 x) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\CollectionViewModel.cs:line 206

**Comment by Viewline-MH** [comment]
I don't get this issue on a laptop. I get this issue on my tablet, which is worrying as this app is designed for use on a tablet. It is crucial that created manholes and assets load quickly and every time and that's not happening at the moment. Do you get this issue on the tablet I sent over?

**Comment by Viewline-MH** [comment]
Okay, I can replicate the issue on my laptop. It is not machine dependant. I can duplicate the issue when I do this: Create a project and then create a number of manholes. Create the next project and then create a manhole with the same reference used on the first manhole on the previous project.

If I do this on laptop or tablet then I get the error message below: 


EntryAssembly: C:\Users\Ian\Desktop\Release\ManholeReport.exe
UnhandledException:
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
  at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at DevExpress.Mvvm.Native.WeakReferenceActionInvoker`1.Execute(T parameter)
  at DevExpress.Mvvm.Native.ActionInvokerBase`1.DevExpress.Mvvm.Native.IActionInvoker.ExecuteIfMatched(Type messageTargetType, Object parameter)
  at DevExpress.Mvvm.Messenger.ActionInvokerCollection.Send(Object message, Type messageTargetType, Object token, Type messageType)
  at DevExpress.Mvvm.Messenger.Send[TMessage](TMessage message, Type messageTargetType, Object token)
  at ManholeReport.Model.Common.ViewModel.SingleObjectViewModelBase`3.Save() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\SingleObjectViewModel.cs:line 113
  at ManholeReport.Model.Common.ViewModel.SingleObjectViewModel`3.SaveAndClose() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\SingleObjectViewModel.partial.cs:line 55
  at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
  at System.Windows.Controls.Primitives.ButtonBase.OnClick()
  at System.Windows.Controls.Button.OnClick()
  at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
  at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
  at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
  at System.Windows.Input.InputManager.ProcessStagingArea()
  at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
  at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
  at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Application.RunDispatcher(Object ignore)
  at System.Windows.Application.RunInternal(Window window)
  at ManholeReport.App.Main() in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\Manholereport\obj\Release\App.g.cs:line 0
InnerException:
	Object reference not set to an instance of an object.
	StackTrace:
	   at ManholeReport.ViewModels.ManholeCollectionViewModel.Manhole_EntityAdded(Object sender, EventArgs e) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\Manholereport\ViewModels\Manhole\ManholeCollectionViewModel.cs:line 199
	  at ManholeReport.Model.Common.ViewModel.CollectionViewModel`3.OnEntityAdded(TPrimaryKey key) in d:\Dropbox\EmmeTechno Projects\Freelancer Project Awarded\Manhole Report Tablet\ManholeReport\ManholeReport.Model\Common\ViewModel\CollectionViewModel.partial.cs:line 32

**Comment by armandomusto** [comment]
I tried several times and I am not able to replictae.

Please Ian get a ne version from this link
https://www.dropbox.com/s/ys5y73b8sdt001t/Manhole%2019.rar?dl=0
maybe someting wrong happend with the latest update.

I am not able to upload on Freelancer for now

**Comment by Viewline-MH** [comment]
Please look at these videos, they show both types of fail.


[Fail1.zip](https://github.com/armandomusto/Manhole-Report/files/124815/Fail1.zip)

**Comment by armandomusto** [comment]
Did you check again with new release?

**Comment by Viewline-MH** [comment]
Just about to do that. I'll be back very shortly. I'll video it if that helps.

**Comment by armandomusto** [comment]
I am able to reproduce, it seems happening only for Manholes

**Comment by Viewline-MH** [comment]
Something happens with Assets as well. I'll check again.

**Comment by armandomusto** [comment]
Yes you are right. We will check and let you know. It seems that the fix we applied needs some improvement

**Comment by Viewline-MH** [comment]
[Fail 4.zip](https://github.com/armandomusto/Manhole-Report/files/124951/Fail.4.zip)

This video holds a clue. Something unexpected happens at 4:18 - 4:20 and the fail occurs not long afterwards. Watch the video very carefully at this time mark and you will see another asset from another project is briefly in view. I flicked right past it, almost missed it. I have seen this before, occasionally.
